local M = {}

function M.highlight(palette, opts)
  return {
    Normal = {
      fg = palette.fg,
      bg = opts.transparent and palette.none or palette.bg,
    },
    SignColumn = { bg = opts.transparent and palette.none or palette.bg },
    MsgArea = {
      fg = palette.fg,
      bg = opts.transparent and palette.none or palette.bg,
    },
    ModeMsg = { fg = palette.fg, bg = palette.bg },
    MsgSeparator = { fg = palette.fg, bg = palette.bg },
    SpellBad = { sp = palette.error, undercurl = true },
    SpellCap = { sp = palette.yellow, undercurl = true },
    SpellLocal = { sp = palette.sign_add, undercurl = true },
    SpellRare = { sp = palette.purple, undercurl = true },
    NormalNC = {
      fg = palette.fg,
      bg = opts.transparent and palette.none or palette.bg,
    },
    Pmenu = { fg = palette.fg, bg = palette.alt_bg },
    PmenuSel = { fg = palette.cyan, bg = palette.gray },
    WildMenu = { fg = palette.cyan, bg = palette.gray },
    CursorLineNr = {
      fg = palette.light_gray,
      bold = true,
    },
    Comment = vim.tbl_extend(
      "force",
      { fg = palette.medium_gray },
      opts.styles.comments
    ),
    Folded = { fg = palette.light_gray, bg = palette.alt_bg },
    FoldColumn = { fg = palette.light_gray, bg = palette.alt_bg },
    LineNr = { fg = palette.medium_gray },
    Whitespace = { fg = palette.gray },
    VertSplit = { fg = palette.border, bg = palette.bg },
    CursorLine = {
      bg = palette.alt_bg,
    },
    CursorColumn = { bg = palette.alt_bg },
    ColorColumn = { bg = palette.alt_bg },
    NormalFloat = {
      bg = opts.transparent and palette.none or palette.alt_bg,
    },
    Visual = { bg = palette.gray },
    VisualNOS = { bg = palette.alt_bg },
    WarningMsg = { fg = palette.error, bg = palette.bg },
    DiffAdd = { bg = palette.accent_green },
    DiffText = { bg = palette.accent_blue },
    DiffChange = {
      fg = palette.sign_change,
      bg = palette.accent_blue,
    },
    DiffDelete = { fg = palette.sign_delete, bg = palette.accent_red },
    QuickFixLine = { bg = palette.accent },
    PmenuSbar = { bg = palette.alt_bg },
    PmenuThumb = { bg = palette.light_gray },
    MatchWord = { underline = true },
    MatchParen = { fg = palette.blue, bg = palette.bg, underline = true },
    MatchWordCur = { underline = true },
    MatchParenCur = { underline = true },
    Cursor = { fg = palette.bg, bg = palette.fg, reverse = false },
    lCursor = { fg = palette.bg, bg = palette.fg, reverse = false },
    CursorIM = { fg = palette.bg, bg = palette.fg, reverse = false },
    TermCursor = { fg = palette.bg, bg = palette.fg, reverse = false },
    TermCursorNC = { fg = palette.alt_bg, bg = palette.alt_bg, reverse = false },
    Conceal = { fg = palette.medium_gray },
    Directory = { fg = palette.blue },
    SpecialKey = { fg = palette.blue },
    Title = { fg = palette.blue },
    ErrorMsg = { fg = palette.error, bg = palette.bg, bold = true },
    Search = { fg = palette.orange, bg = palette.alt_bg },
    IncSearch = { fg = palette.alt_bg, bg = palette.sign_delete },
    Substitute = { fg = palette.alt_bg, bg = palette.orange },
    MoreMsg = { fg = palette.cyan },
    Question = { fg = palette.cyan },
    EndOfBuffer = { fg = palette.bg },
    NonText = { fg = palette.bg },
    Variable = vim.tbl_extend("force", { fg = palette.fg }, opts.styles.variables),
    String = { fg = palette.pink },
    Character = { fg = palette.green },
    Constant = { fg = palette.fg },
    Number = { fg = palette.yellow },
    Boolean = { fg = palette.yellow },
    Float = { fg = palette.yellow },
    Identifier = { fg = palette.fg },
    Function = vim.tbl_extend("force", { fg = palette.orange }, opts.styles.functions),
    Operator = { fg = palette.fg },
    Type = vim.tbl_extend("force", { fg = palette.orange }, opts.styles.type),
    StorageClass = { fg = palette.teal },
    Structure = { fg = palette.teal },
    Typedef = { fg = palette.orange },
    Keyword = vim.tbl_extend("force", { fg = palette.teal }, opts.styles.keywords),
    Statement = { fg = palette.teal },
    Conditional = { fg = palette.teal },
    Repeat = { fg = palette.teal },
    Label = { fg = palette.fg },
    Exception = { fg = palette.red },
    Include = { fg = palette.teal },
    PreProc = { fg = palette.teal },
    Define = { fg = palette.teal },
    Macro = { fg = palette.cyan },
    PreCondit = { fg = palette.medium_gray },
    Special = { fg = palette.fg },
    SpecialChar = { fg = palette.pink },
    Tag = { fg = palette.blue },
    Debug = { fg = palette.red },
    Delimiter = { fg = palette.fg },
    SpecialComment = vim.tbl_extend(
      "force",
      { fg = palette.medium_gray },
      opts.styles.comments
    ),
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = palette.cyan, bg = palette.bg, bold = true },
    Todo = { fg = palette.red, bg = palette.bg, bold = true },
    Error = { fg = palette.error, bg = palette.bg, bold = true },
    TabLine = { fg = palette.gray, bg = palette.alt_bg },
    TabLineSel = { fg = palette.white, bg = palette.alt_bg },
    TabLineFill = { fg = palette.white, bg = palette.alt_bg },
    WinSeparator = { fg = palette.border, bg = palette.bg },
    DiagnosticFloatingError = { fg = palette.error },
    FloatBorder = { fg = palette.border_active },
  }
end

return M
